image: "registry.michelada.io/michelada/dockerfiles/ci/rails:3.0.2"

services:
  - postgres

stages:
  - test

variables:
  RAILS_ENV: 'test'
  DB_HOST: postgres
  POSTGRES_PASSWORD: soundcloud2021
  POSTGRES_USER: karlarosas

before_script:
  - bundle install

rubocop:
  stage: test
  script:
    - yarn install
    - bundle exec rubocop

test:
  stage: test
  script:
    - yarn install
    - bundle exec rake db:create db:schema:load
    - bundle exec rake test